from .animgender import AnimGender
from .character import Character
from .corenlp import CoreNLP
from .grammar_numb import Grammatical_number
from .nernpid import NerNpID
from .tokenizer import Tokenizer
from .quote import Quote
from .quoted_speech import Quoted_Speech
from .quoted_speech_ht import Quoted_Speech_ht
from .sentiment import Sentiment
from .first_person import First_person
